// Core data types for WordGotchi

// ============================================================================
// Core Data Types
// ============================================================================

/**
 * Emotion representation with seven basic emotions
 * Each emotion value ranges from 0 to 1
 */
export interface EmotionVector {
  joy: number;        // 0-1
  sadness: number;    // 0-1
  anger: number;      // 0-1
  fear: number;       // 0-1
  surprise: number;   // 0-1
  disgust: number;    // 0-1
  trust: number;      // 0-1
  lastUpdated: number; // timestamp
}

/**
 * Gotchi state representing the virtual pet's current status
 */
export interface GotchiState {
  id: string;
  stage: 1 | 2; // 1: Obake, 2: Boofer
  feedingCount: number;
  emotionVector: EmotionVector;
  createdAt: number;
}

/**
 * Record of a single feeding session
 */
export interface FeedingRecord {
  id: string;
  timestamp: number;
  inputText: string;
  words: string[];
  emotionAnalysis: EmotionVector;
}

/**
 * Art expression generated by the Gotchi
 */
export interface ArtExpression {
  id: string;
  timestamp: number;
  imageUrl: string;
  prompt: string;
  dominantEmotion: string;
}

/**
 * Poetry expression generated by the Gotchi
 */
export interface PoetryExpression {
  id: string;
  timestamp: number;
  lines: string[];
  sourceText: string;
  emotionContext: EmotionVector;
}

// ============================================================================
// Service Interfaces
// ============================================================================

/**
 * Service for emotion analysis and manipulation
 */
export interface EmotionService {
  analyzeText(text: string): Promise<EmotionVector>;
  applyDecay(vector: EmotionVector, daysSince: number): EmotionVector;
  mergeEmotions(current: EmotionVector, newEmotions: EmotionVector): EmotionVector;
  getDominantEmotion(vector: EmotionVector): string;
}

/**
 * Service for generating artistic expressions
 */
export interface ExpressionService {
  generateArt(emotionVector: EmotionVector): Promise<ArtExpression>;
  generatePoetry(inputText: string, emotionVector: EmotionVector): Promise<PoetryExpression>;
  buildArtPrompt(emotionVector: EmotionVector): string;
}

/**
 * Service for persistent storage operations
 */
export interface StorageService {
  saveGotchi(state: GotchiState): void;
  loadGotchi(): GotchiState | null;
  saveFeedingRecord(record: FeedingRecord): void;
  getFeedingHistory(limit: number): FeedingRecord[];
  saveExpression(expression: ArtExpression | PoetryExpression): void;
  getExpressions(limit: number): (ArtExpression | PoetryExpression)[];
  checkStorageSize(): number;
  pruneOldData(): void;
}

// ============================================================================
// Animation System
// ============================================================================

/**
 * Point in 2D space
 */
export interface Point {
  x: number;
  y: number;
}

/**
 * Rectangle bounds
 */
export interface Rect {
  x: number;
  y: number;
  width: number;
  height: number;
}

/**
 * Position of a word on the canvas
 */
export interface WordPosition {
  word: string;
  position: Point;
}

/**
 * Controller for all animations in the application
 */
export interface AnimationController {
  // Word feeding animations
  scatterWords(words: string[], canvasBounds: Rect): WordPosition[];
  animateWordToGotchi(word: string, from: Point, to: Point): Promise<void>;
  playEatingAnimation(): Promise<void>;
  
  // Emote animations
  playEmote(emotion: string): Promise<void>;
  
  // Gotchi idle animation
  startFloatingAnimation(): void;
  stopFloatingAnimation(): void;
  
  // Evolution animation
  playEvolutionAnimation(fromStage: number, toStage: number): Promise<void>;
  
  // Glow effects
  updateGlowEffect(emotionVector: EmotionVector): void;
}
